freight/urls.py
"""Routes for Freight."""

from django.urls import path

from . import views

app_name = "freight"

urlpatterns = [
    path("", views.index, name="index"),
    path(
        "setup_contract_handler",
        views.setup_contract_handler,
        name="setup_contract_handler",
    ),
    path("add_location", views.add_location, name="add_location"),
    path("add_location_2", views.add_location_2, name="add_location_2"),
    path("calculator", views.calculator, name="calculator"),
    path("calculator/<int:pricing_pk>", views.calculator, name="calculator"),
    path("contract_list_all", views.contract_list_all, name="contract_list_all"),
    path("contract_list_user", views.contract_list_user, name="contract_list_user"),
    path(
        "contract_list_data/<str:category>",
        views.contract_list_data,
        name="contract_list_data",
    ),
    path("statistics", views.statistics, name="statistics"),
    path(
        "statistics_routes_data",
        views.statistics_routes_data,
        name="statistics_routes_data",
    ),
    path(
        "statistics_pilots_data",
        views.statistics_pilots_data,
        name="statistics_pilots_data",
    ),
    path(
        "statistics_pilot_corporations_data",
        views.statistics_pilot_corporations_data,
        name="statistics_pilot_corporations_data",
    ),
    path(
        "statistics_customer_data",
        views.statistics_customer_data,
        name="statistics_customer_data",
    ),
]

freight/forms.py
"""Forms for Freight."""

import math

from django import forms
from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator

from .models import Pricing


class CalculatorForm(forms.Form):
    """A form for the price calculator."""

    pricing = forms.ModelChoiceField(
        queryset=Pricing.objects.select_related("start_location", "end_location")
        .filter(is_active=True)
        .order_by("start_location__name", "end_location__name"),
        label="Route",
        help_text="Pick a route for your courier contract",
        empty_label=None,
    )
    volume = forms.IntegerField(
        help_text="Est. volume of your cargo in m3",
        required=False,
        validators=[MinValueValidator(0)],
    )
    collateral = forms.IntegerField(
        help_text=(
            "Collateral in ISK, must be roughly equal to the est. "
            "value of your cargo"
        ),
        required=False,
        validators=[MinValueValidator(0)],
    )

    def clean(self):
        pricing = self.cleaned_data.get("pricing")
        if pricing:
            issue_prefix = "⚠ Issues:"

            if pricing.requires_volume() and self.cleaned_data["volume"] is None:
                raise ValidationError(f"{issue_prefix} volume is required")

            if (
                pricing.requires_collateral()
                and self.cleaned_data["collateral"] is None
            ):
                raise ValidationError(f"{issue_prefix} collateral is required")

            volume = self.cleaned_data["volume"]
            collateral = self.cleaned_data["collateral"]
            issues = pricing.get_contract_price_check_issues(volume, collateral)

            if issues:
                raise ValidationError(f"{issue_prefix} {', '.join(issues)}")

    def get_calculated_data(self, pricing: object) -> tuple:
        """Return calculated pricing data."""
        if self.is_valid():
            if self.cleaned_data["volume"]:
                volume = int(self.cleaned_data["volume"])
            else:
                volume = 0
            if self.cleaned_data["collateral"]:
                collateral = int(self.cleaned_data["collateral"])
            else:
                collateral = 0
            price = (
                math.ceil(pricing.get_calculated_price(volume, collateral) / 1000000)
                * 1000000
            )

        else:
            volume = None
            collateral = None
            price = None

        return volume, collateral, price


class AddLocationForm(forms.Form):
    """A form for adding a new location."""

    location_id = forms.IntegerField(
        label="Location ID",
        help_text="Eve Online ID for a station or an Upwell structure",
    )

freight/templates/freight/add_location.html
{% extends 'freight/base.html' %}
{% load i18n %}
{% load humanize %}
{% load bootstrap %}

{% block details %}
    <form class="form" action="{% url 'freight:add_location_2' %}" method="POST">
        {% csrf_token %}
        {{ form|bootstrap }}
        <button class="btn btn-success btn-block" type="submit">
            {% translate "Add / Update Location" %}
        </button>
        <p class="text-muted">
            {% blocktranslate %}Accessing structures with token from {{ token_char_name }}{% endblocktranslate %}
        </p>
    </form>
{% endblock %}

freight/templates/freight/base.html
{% extends 'allianceauth/base.html' %}
{% load i18n %}
{% block page_title %}{{ app_title }}{% endblock %}

{% block content %}
    <br />
    {% include 'freight/partials/menu.html' %}
    <h2>{{ page_title }}</h2>
    {% block details %}{% endblock %}
{% endblock %}

freight/templates/freight/calculator.html
{% extends 'freight/base.html' %}
{% load i18n %}
{% load humanize %}
{% load bootstrap %}
{% load static %}
{% load freight_filters %}

{% block details %}
    <form id="form_calculator" class="form" action="{% url 'freight:calculator' %}" method="POST">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-6">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">{% translate "Calculator" %}</h3>
                    </div>
                    <div class="panel-body">
                        {% if has_pricing %}
                            {{ form|bootstrap }}
                            <br>
                            <p><strong>{% translate "Reward" %}</strong></p>
                            <h2 id="text_price">
                                <span id="text_price_2">{{ price|formatnumber:"0"|default_if_none:"-" }}
                                    &nbsp;{% translate "ISK" %}
                                </span>
                                <span class="copy_to_clipboard" data-clipboard-text="{{ price }}">
                                    &nbsp;&nbsp;<i class="far fa-copy"></i></span>
                                </span>
                            </h2>
                                <button class="btn btn-success btn-lg" type="submit">
                                    {% translate "Click To Calculate Reward!" %}
                                </button>
                        {% else %}
                            <p class="text-warning">
                                {% translate "Please define a pricing/route!" %}
                            </p>
                        {% endif %}
                    </div>
                </div>
            </div>

            <div class="col-md-6">

                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">{% translate "Pricing details" %}</h3>
                    </div>

                    <div class="panel-body" style="min-height: 100px;">

                        {% if pricing %}
                            <dl class="dl-horizontal">
                                {% if pricing.is_bidirectional %}
                                    <dt>{% translate "From / To:" %}</dt>
                                {% else %}
                                    <dt>{% translate "From:" %}</dt>
                                {% endif %}

                                <dd>{{ pricing.start_location }}</dd>

                                {% if pricing.is_bidirectional %}
                                    <dt>{% translate "From / To:" %}</dt>
                                {% else %}
                                    <dt>{% translate "To:" %}</dt>
                                {% endif %}
                                <dd>{{ pricing.end_location }}</dd>

                                <dt><dt>{% translate "Both directions:" %}</dt></dt>
                                <dd>{{ pricing.is_bidirectional|yesno }}</dd>
                                <br>

                                {% if pricing.price_min != None %}
                                    <dt>{% translate "Minimum price:" %}</dt>
                                    <dd>
                                        {{ pricing.price_min|formatnumber:"0" }}&nbsp;{% translate "ISK" %}
                                    </dd>
                                {% endif %}

                                {% if pricing.price_base != None %}
                                    {% if pricing.is_fix_price %}
                                        <dt>{% translate "Fix price:" %}</dt>
                                    {% else %}
                                        <dt>{% translate "Base price:" %}</dt>
                                    {% endif %}
                                    <dd>{{ pricing.price_base|formatnumber:"0" }}
                                        &nbsp;{% translate "ISK" %}
                                    </dd>
                                {% endif %}

                                {% if pricing_price_per_volume_eff != None %}
                                    <dt>{% translate "Price add-on per m3:" %}</dt>
                                    <dd>
                                        {{ pricing_price_per_volume_eff|formatnumber:"0" }}
                                        &nbsp;{% translate "ISK" %}
                                    </dd>
                                {% endif %}

                                {% if pricing.price_per_collateral_percent != None %}
                                    <dt>{% translate "Price add-on collateral:" %}</dt>
                                    <dd>{{ pricing.price_per_collateral_percent }} %</dd>
                                {% endif %}

                                <br>
                                {% if pricing.volume_min != None %}
                                    <dt>{% translate "Min Volume:" %}</dt>
                                    <dd>
                                        {{ pricing.volume_min|formatnumber:"0"|default_if_none:"-" }}
                                        &nbsp;{% translate "m3" %}
                                    </dd>
                                {% endif %}

                                {% if pricing.volume_max != None %}
                                    <dt>{% translate "Max Volume:" %}</dt>
                                    <dd>
                                        {{ pricing.volume_max|formatnumber:"0"|default_if_none:"-" }}
                                        &nbsp;{% translate "m3" %}
                                    </dd>
                                {% endif %}

                                {% if pricing.collateral_min != None %}
                                    <dt>{% translate "Min. Collateral:" %}</dt>
                                    <dd>
                                        {{ pricing.collateral_min|formatnumber:"0" }}
                                        &nbsp;{% translate "ISK" %}
                                    </dd>
                                {% endif %}

                                {% if pricing.collateral_max != None %}
                                    <dt>{% translate "Max. Collateral:" %}</dt>
                                    <dd>
                                        {{ pricing.collateral_max|formatnumber:"0" }}
                                        &nbsp;{% translate "ISK" %}
                                    </dd>
                                {% endif %}

                                <br>

                                {% if pricing.details %}
                                    <dt>{% translate "Additional Instructions:" %}</dt>
                                    <dd>{{ pricing.details|linebreaks }}</dd>
                                {% endif %}

                            </dl>

                        {% else %}
                            <p class="text-warning">{% translate "Please define a pricing/route!" %}</p>
                        {% endif %}

                    </div>
                </div>

                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">{% translate "Your contract" %}</h3>
                    </div>
                    <div class="panel-body" style="min-height: 100px;">
                        {% if price != None %}
                            <dl class="dl-horizontal">
                                <dt>{% translate "Contract Type:" %}</dt>
                                <dd>{% translate "Courier" %}</dd>

                                <dt>{% translate "Availability:" %}</dt>
                                <dd>{{ availability }}</dd>

                                <dt>{% translate "Location:" %}</dt>
                                <dd>
                                    {{ pricing.start_location }}
                                    <span class="copy_to_clipboard" data-clipboard-text="{{ pricing.start_location }}">
                                        &nbsp;&nbsp;<i class="far fa-copy"></i></span>
                                    </span>
                                </dd>

                                <hr>

                                <dt>{% translate "Ship To:" %}</dt>
                                <dd>
                                    {{ pricing.end_location }}
                                    <span class="copy_to_clipboard" data-clipboard-text="{{ pricing.end_location }}">
                                        &nbsp;&nbsp;<i class="far fa-copy"></i></span>
                                    </span>
                                </dd>

                                <dt>{% translate "Reward:" %}</dt>
                                <dd>
                                    {{ price|formatnumber:"0"|default_if_none:"???" }}
                                    &nbsp;{% translate "ISK" %}
                                    <span class="copy_to_clipboard" data-clipboard-text="{{ price }}">
                                        &nbsp;&nbsp;<i class="far fa-copy"></i></span>
                                    </span>
                                </dd>

                                <dt>{% translate "Collateral:" %}</dt>
                                <dd>
                                    {{ collateral|formatnumber:"0"|default_if_none:"???" }}
                                    &nbsp;{% translate "ISK" %}
                                    <span class="copy_to_clipboard" data-clipboard-text="{{ collateral }}">
                                        &nbsp;&nbsp;<i class="far fa-copy"></i></span>
                                    </span>
                                </dd>

                                {% if pricing.days_to_expire %}
                                    <dt>{% translate "Expiration:" %}</dt>
                                    <dd>{{ pricing.days_to_expire }} {% translate "days" %} ({{ expires_on|date:'Y-m-d' }})</dd>
                                {% endif %}

                                {% if pricing.days_to_complete %}
                                    <dt>{% translate "Days to complete:" %}</dt>
                                    <dd>
                                        {{ pricing.days_to_complete|default_if_none:"-" }}
                                        <span class="copy_to_clipboard" data-clipboard-text="{{ pricing.days_to_complete }}">
                                            &nbsp;&nbsp;<i class="far fa-copy"></i></span>
                                        </span>
                                    </dd>
                                {% endif %}

                                {% if pricing.requires_volume %}
                                    <dt>{% translate "Volume:" %}</dt>
                                    <dd>
                                        {{ volume|formatnumber:"0"|default_if_none:"???" }}
                                        &nbsp;{% translate "m3" %}
                                    </dd>
                                {% endif %}

                                <hr>
                                {% translate "Note that this route is bidirectional, so Location and Destination can be switched." %}
                            </dl>

                        {% else %}
                            <p class="text-muted">{% translate "No price calculated yet" %}</p>
                        {% endif %}
                    </div>
                </div>

            </div>
        </div>

    </form>
<br>

{% endblock %}

{% block extra_javascript %}
    {% include 'bundles/clipboard-js.html' %}

    <script type="application/javascript">
        const clipboard = new ClipboardJS('.copy_to_clipboard');

        clipboard.on('success', function (e) {
            e.clearSelection();
        });

        clipboard.on('error', function (e) {
            console.error('Action:', e.action);
            console.error('Trigger:', e.trigger);
        });

        $(document).ready(function(){
            /* redirecting to updated calculator view with chosen pricing */
            $("#id_pricing").change(function(){
                let value = $("#id_pricing").val();
                if (value == null) {
                    value = 0;
                }
                window.location.replace(
                    "{% url 'freight:calculator' 0 %}".replace("0", value)
                );
            });

        });
    </script>
{% endblock %}

{% block extra_css %}
    <link href="{% static 'freight/css/kalkoken.css' %}" type="text/css" rel="stylesheet">
    <link href="{% static 'freight/css/calculator.css' %}" type="text/css" rel="stylesheet">
{% endblock %}

{% block extra_script %}
{% endblock %}

freight/templates/freight/contracts_all.html
{% extends 'freight/base.html' %}
{% load i18n %}
{% load humanize %}
{% load static %}

{% block details %}

    <!-- Nav tabs -->
    <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="active">
            <a href="#active_contracts" aria-controls="active_contracts" role="tab" data-toggle="tab">
                {% translate "Active" %}
            </a>
        </li>
        <li role="presentation">
            <a href="#all_contracts" aria-controls="all_contracts" role="tab" data-toggle="tab">
                {% translate "All" %}
            </a>
        </li>
    </ul>

    <div class="panel panel-default panel-tab">
        <div class="panel-body">
            <div class="tab-content">
                <div role="tabpanel" class="tab-pane active" id="active_contracts">
                    {% include "freight/partials/contract_table.html" with tab_name="tab_active_contracts" %}
                </div>
                <div role="tabpanel" class="tab-pane" id="all_contracts">
                    {% include "freight/partials/contract_table.html" with tab_name="tab_all_contracts" %}
                </div>
            </div>
        </div>
    </div>

    {% include "freight/partials/contracts_legend.html" %}


{% endblock %}

{% block extra_javascript %}

    {% include "freight/partials/contracts_js_includes.html" %}
    {% include "freight/partials/global_js.html" %}

    <script type="application/javascript">
        $(document).ready(function(){
            createContractsDataTable(
                "tab_active_contracts", "{% url 'freight:contract_list_data' 'active' %}"
            )
            createContractsDataTable(
                "tab_all_contracts", "{% url 'freight:contract_list_data' 'all' %}"
            )
        });
    </script>
{% endblock %}

{% block extra_css %}
    {% include 'bundles/datatables-css.html' %}

    <link href="{% static 'freight/css/kalkoken.css' %}" type="text/css" rel="stylesheet">
    <link href="{% static 'freight/css/contracts.css' %}" type="text/css" rel="stylesheet">
{% endblock %}

{% block extra_script %}
{% endblock %}

freight/templates/freight/contracts_user.html
{% extends 'freight/base.html' %}
{% load i18n %}
{% load humanize %}
{% load static %}

{% block details %}

    <!-- Nav tabs -->
    <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="active">
            <a href="#active_contracts" aria-controls="active_contracts" role="tab" data-toggle="tab">
                {{ user_name }}
            </a>
        </li>
    </ul>

    <div class="panel panel-default panel-tab">
        <div class="panel-body">
            <div class="tab-content">
                <div role="tabpanel" class="tab-pane active" id="active_contracts">
                    {% include "freight/partials/contract_table.html" with tab_name="tab_user_contracts" %}
                </div>
            </div>
        </div>
    </div>

    {% include "freight/partials/contracts_legend.html" %}


{% endblock %}

{% block extra_javascript %}

    {% include "freight/partials/contracts_js_includes.html" %}
    {% include "freight/partials/global_js.html" %}

    <script type="application/javascript">
        $(document).ready(function(){
            createContractsDataTable(
                "tab_user_contracts", "{% url 'freight:contract_list_data' 'user' %}"
            )
        });
    </script>
{% endblock %}

{% block extra_css %}
    {% include 'bundles/datatables-css.html' %}

    <link href="{% static 'freight/css/kalkoken.css' %}" type="text/css" rel="stylesheet">
    <link href="{% static 'freight/css/contracts.css' %}" type="text/css" rel="stylesheet">
{% endblock %}

{% block extra_script %}
{% endblock %}