freight/urls.py
"""Routes for Freight."""

from django.urls import path

from . import views

app_name = "freight"

urlpatterns = [
    path("", views.index, name="index"),
    path(
        "setup_contract_handler",
        views.setup_contract_handler,
        name="setup_contract_handler",
    ),
    path("add_location", views.add_location, name="add_location"),
    path("add_location_2", views.add_location_2, name="add_location_2"),
    path("calculator", views.calculator, name="calculator"),
    path("calculator/<int:pricing_pk>", views.calculator, name="calculator"),
    path("contract_list_all", views.contract_list_all, name="contract_list_all"),
    path("contract_list_user", views.contract_list_user, name="contract_list_user"),
    path(
        "contract_list_data/<str:category>",
        views.contract_list_data,
        name="contract_list_data",
    ),
    path("statistics", views.statistics, name="statistics"),
    path(
        "statistics_routes_data",
        views.statistics_routes_data,
        name="statistics_routes_data",
    ),
    path(
        "statistics_pilots_data",
        views.statistics_pilots_data,
        name="statistics_pilots_data",
    ),
    path(
        "statistics_pilot_corporations_data",
        views.statistics_pilot_corporations_data,
        name="statistics_pilot_corporations_data",
    ),
    path(
        "statistics_customer_data",
        views.statistics_customer_data,
        name="statistics_customer_data",
    ),
]

freight/models/contracts.py
"""Contract models."""

# pylint: disable = import-outside-toplevel, ungrouped-imports

import json
from datetime import timedelta
from typing import List, Optional, Set
from urllib.parse import urljoin

import dhooks_lite

from django.db import models, transaction
from django.urls import reverse
from django.utils.timezone import now
from django.utils.translation import gettext_lazy as _

from allianceauth.authentication.models import User
from allianceauth.eveonline.models import EveCharacter, EveCorporationInfo
from allianceauth.services.hooks import get_extension_logger
from app_utils.datetime import DATETIME_FORMAT
from app_utils.django import app_labels
from app_utils.helpers import humanize_number
from app_utils.logging import LoggerAddTag
from app_utils.urls import site_absolute_url

from freight import __title__
from freight.app_settings import (
    DISCORDPROXY_HOST,
    DISCORDPROXY_PORT,
    FREIGHT_APP_NAME,
    FREIGHT_DISCORD_CUSTOMERS_WEBHOOK_URL,
    FREIGHT_DISCORD_DISABLE_BRANDING,
    FREIGHT_DISCORD_MENTIONS,
    FREIGHT_DISCORD_WEBHOOK_URL,
    FREIGHT_DISCORDPROXY_ENABLED,
    FREIGHT_HOURS_UNTIL_STALE_STATUS,
)
from freight.constants import AVATAR_SIZE
from freight.managers import ContractManager

from .contract_handlers import ContractHandler
from .routes import Location, Pricing

if "discord" in app_labels():
    from allianceauth.services.modules.discord.models import DiscordUser
else:
    DiscordUser = None  # pylint: disable=invalid-name

try:
    from discordproxy.client import DiscordClient
    from discordproxy.discord_api_pb2 import Embed
    from discordproxy.exceptions import DiscordProxyException
    from google.protobuf import json_format
except ImportError:
    DiscordClient = None

logger = LoggerAddTag(get_extension_logger(__name__), __title__)


class Contract(models.Model):
    """An Eve Online courier contract with additional meta data"""

    class Status(models.TextChoices):
        """A contract status."""

        OUTSTANDING = "outstanding", _("outstanding")
        IN_PROGRESS = "in_progress", _("in progress")
        FINISHED_ISSUER = "finished_issuer", _("finished issuer")
        FINISHED_CONTRACTOR = "finished_contractor", _("finished contractor")
        FINISHED = "finished", _("finished")
        CANCELED = "canceled", _("canceled")
        REJECTED = "rejected", _("rejected")
        FAILED = "failed", _("failed")
        DELETED = "deleted", _("deleted")
        REVERSED = "reversed", _("reversed")

        @classmethod
        def completed(cls) -> Set["Contract.Status"]:
            """Return status representing a completed contract."""
            return {
                cls.FINISHED_ISSUER,
                cls.FINISHED_CONTRACTOR,
                cls.FINISHED_ISSUER,
                cls.CANCELED,
                cls.REJECTED,
                cls.DELETED,
                cls.FINISHED,
                cls.FAILED,
            }

        @classmethod
        def for_customer_notification(cls) -> Set["Contract.Status"]:
            """Return status relevant for custom notification."""
            return {cls.OUTSTANDING, cls.IN_PROGRESS, cls.FINISHED, cls.FAILED}

    EMBED_COLOR_PASSED = 0x008000
    EMBED_COLOR_FAILED = 0xFF0000

    handler = models.ForeignKey(
        ContractHandler, on_delete=models.CASCADE, related_name="contracts"
    )
    contract_id = models.IntegerField(verbose_name=_("contract ID"))

    acceptor = models.ForeignKey(
        EveCharacter,
        on_delete=models.CASCADE,
        default=None,
        null=True,
        blank=True,
        verbose_name=_("acceptor"),
        related_name="contracts_acceptor",
        help_text=_("Character of acceptor or None if accepted by corp"),
    )
    acceptor_corporation = models.ForeignKey(
        EveCorporationInfo,
        on_delete=models.CASCADE,
        default=None,
        null=True,
        blank=True,
        verbose_name=_("acceptor corporation"),
        related_name="contracts_acceptor_corporation",
        help_text=_("Corporation of acceptor"),
    )
    collateral = models.FloatField(verbose_name=_("collateral"))
    date_accepted = models.DateTimeField(
        default=None,
        null=True,
        blank=True,
        verbose_name=_("date accepted"),
    )
    date_completed = models.DateTimeField(
        default=None,
        null=True,
        blank=True,
        verbose_name=_("date completed"),
    )
    date_expired = models.DateTimeField(verbose_name=_("date expired"))
    date_issued = models.DateTimeField(
        verbose_name=_("date issues"),
    )
    date_notified = models.DateTimeField(
        default=None,
        null=True,
        blank=True,
        db_index=True,
        verbose_name=_("date notified"),
        help_text=_("Datetime of latest notification, None = none has been sent"),
    )
    days_to_complete = models.IntegerField(
        verbose_name=_("days to complete"),
    )
    end_location = models.ForeignKey(
        Location,
        on_delete=models.CASCADE,
        verbose_name=_("end location"),
        related_name="contracts_end_location",
    )
    for_corporation = models.BooleanField(verbose_name=_("for corporation"))
    issuer_corporation = models.ForeignKey(
        EveCorporationInfo,
        on_delete=models.CASCADE,
        verbose_name=_("issuer corporation"),
        related_name="contracts_issuer_corporation",
    )
    issuer = models.ForeignKey(
        EveCharacter,
        on_delete=models.CASCADE,
        verbose_name=_("issuer"),
        related_name="contracts_issuer",
    )
    issues = models.TextField(
        default=None,
        null=True,
        blank=True,
        verbose_name=_("issues"),
        help_text=_("List or price check issues as JSON array of strings or None"),
    )
    pricing = models.ForeignKey(
        Pricing,
        on_delete=models.SET_DEFAULT,
        default=None,
        null=True,
        blank=True,
        verbose_name=_("pricing"),
        related_name="contracts",
    )
    reward = models.FloatField(verbose_name=_("reward"))
    start_location = models.ForeignKey(
        Location,
        on_delete=models.CASCADE,
        verbose_name=_("start location"),
        related_name="contracts_start_location",
    )
    status = models.CharField(
        max_length=32,
        choices=Status.choices,
        db_index=True,
        verbose_name=_("status"),
    )
    title = models.CharField(
        max_length=100,
        default=None,
        null=True,
        blank=True,
        verbose_name=_("title"),
    )
    volume = models.FloatField(verbose_name=_("volume"))

    objects = ContractManager()

    class Meta:
        indexes = [models.Index(fields=["status"])]
        unique_together = (("handler", "contract_id"),)
        verbose_name = _("contract")
        verbose_name_plural = _("contracts")

    def __str__(self) -> str:
        return (
            f"{self.contract_id}: {self.start_location.solar_system_name} "
            f"-> {self.end_location.solar_system_name}"
        )

    def __repr__(self) -> str:
        return (
            f"{self.__class__.__name__}(contract_id={self.contract_id}, "
            f"start_location={self.start_location.solar_system_name}, "
            f"end_location={self.end_location.solar_system_name})"
        )

    @property
    def is_completed(self) -> bool:
        """whether this contract is completed or active"""
        return self.status in self.Status.completed()

    @property
    def is_in_progress(self) -> bool:
        """Return True if this contract is in progress, else False."""
        return self.status == self.Status.IN_PROGRESS

    @property
    def is_failed(self) -> bool:
        """Return True if this contract is failed, else False."""
        return self.status == self.Status.FAILED

    @property
    def has_expired(self) -> bool:
        """returns true if this contract is expired"""
        return self.date_expired < now()

    @property
    def has_pricing(self) -> bool:
        """Return True if this contract has pricing, else False."""
        return bool(self.pricing)

    @property
    def has_pricing_errors(self) -> bool:
        """Return True if this contract has pricing errors, else False."""
        return bool(self.issues)

    # @property
    # def hours_issued_2_completed(self) -> float:
    #     if self.date_completed:
    #         delta = self.date_completed - self.date_issued
    #         return delta.days * 24 + (delta.seconds / 3600)

    #     return None

    @property
    def date_latest(self) -> bool:
        """latest status related date of this contract"""
        if self.date_completed:
            date = self.date_completed
        elif self.date_accepted:
            date = self.date_accepted
        else:
            date = self.date_issued

        return date

    @property
    def has_stale_status(self) -> bool:
        """whether the status of this contract has become stale"""
        return self.date_latest < now() - timedelta(
            hours=FREIGHT_HOURS_UNTIL_STALE_STATUS
        )

    @property
    def acceptor_name(self) -> str:
        "returns the name of the acceptor character or corporation or None"

        if self.acceptor:
            name = self.acceptor.character_name
        elif self.acceptor_corporation:
            name = self.acceptor_corporation.corporation_name
        else:
            name = None

        return name

    def get_price_check_issues(self, pricing: Pricing) -> Optional[List[str]]:
        """Return list of pricing issues."""
        return pricing.get_contract_price_check_issues(
            self.volume, self.collateral, self.reward
        )

    def get_issue_list(self) -> list:
        """returns current pricing issues as list of strings"""
        if self.issues:
            return json.loads(self.issues)
        return []

    def _generate_embed_description(self) -> object:

freight/templates/freight/partials/contract_table.html
{% load i18n %}

<div class="table-responsive">
    <table class="table table-striped table-width-fix tab-contract" id="{{ tab_name }}">
        <thead>
            <tr>
                <th>{% translate "Status" %}</th>
                <th>{% translate "Start" %}</th>
                <th>{% translate "Destination" %}</th>
                <th>{% translate "Reward ISK" %}</th>
                <th>{% translate "Collateral ISK" %}</th>
                <th>{% translate "Volume m3" %}</th>
                <th>{% translate "Contract Check" %}</th>
                <th>{% translate "Issued On" %}</th>
                <th>{% translate "Expires On" %}</th>
                <th>{% translate "Issued By" %}</th>
                <th>{% translate "Accepted On" %}</th>
                <th>{% translate "Accepted By" %}</th>
            </tr>
        </thead>
        <tbody>
        </tbody>
    </table>
</div>

freight/templates/freight/partials/contracts_js_includes.html
{% load static %}

{% include 'bundles/moment-js.html' with locale=True %}
{% include 'bundles/datatables-js.html' %}
{% include 'bundles/filterdropdown-js.html' %}

<script type="application/javascript" src="{% static 'freight/vendor/datatables/datetime.js' %}"></script>
<script type="application/javascript" src="{% static 'freight/js/contracts.js' %}"></script>

freight/templates/freight/partials/contracts_legend.html
{% load i18n %}

<p class="text-muted">
    {% translate "Contract check:" %}
    <span class="glyphicon glyphicon-ok" aria-hidden="true"></span> {% translate "OK" %} |
    <span class="glyphicon glyphicon-warning-sign" aria-hidden="true"></span> {% translate "Errors" %} |
    {% translate "If they are errors you find them in the tooltip of icon" %} |
    <strong>-</strong> {% translate "No contract check performed" %}
</p>
<p class="text-muted">
    {% translate "Notes:" %}
    <span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>
    {% translate "If icon is shown you can hover with the mouse over it to see the notes." %}
</p>
<p class="text-muted">
    {% translate "Color code:" %}
    <span class="text-info">{% translate "In Progress" %}</span> |
    <span class="text-warning">{% translate "failed" %}</span> |
    <span class="text-success">{% translate "completed" %}</span>
</p>

freight/templates/freight/partials/global_js.html
<!-- Global Javascript. Implemented as template, so we can use tags, filters and context. -->

<script type="text/javascript">
    /* Global constants */
    const DEFAULT_LENGTH_MENU = [[10, 25, 50, 100 -1], [10, 25, 50, 100, "All"]]
    const DEFAULT_PAGE_LENGTH = 50
    const B_DIVIDER = 9

    // Format ISK values for output
    // magnitude: show value with given magnitude, else magnitude will be calculated
    function formatisk(data, magnitude=null) {
        if ( data != null ) {
            const power_map = {'t': 12, 'b': 9, 'm': 6, 'k': 3, '': 0}
            if (!power_map.hasOwnProperty(magnitude)) {
                if (data >= 10 ** 12) magnitude = 't';
                else if (data >= 10 ** 9) magnitude = 'b';
                else if (data >= 10 ** 6) magnitude = 'm';
                else if (data >= 10 ** 3) magnitude = 'k';
                else magnitude = '';
            }
            return (data / (10 ** power_map[magnitude])).toLocaleString(
                'en-US', {minimumFractionDigits: 1, maximumFractionDigits: 1}
            ) + magnitude;
        }
        else return "";
    }

    // sum numbers in column and write result in footer row
    // Args:
    // - api: current api object
    // - columnIdx: Index number of columns to sum, starts with 0
    // - format: format of output. either 'number' or 'isk'
    function dataTableFooterSumColumn(api, columnIdx, format='number') {
        // Remove the formatting to get integer data for summation
        const intVal = function (i) {
            return typeof i === 'string' ?
                i.replace(/[\$,]/g, '') * 1 :
                typeof i === 'number' ?
                    i : 0;
        };

        const columnTotal = api
            .column(columnIdx)
            .data()
            .reduce(function (a, b) {
                    return intVal(a) + intVal(b);
                },
                0
            );
        let result;
        if (format == 'isk'){
            result = formatisk(columnTotal)
        } else {
            result = columnTotal.toLocaleString('en-US', {maximumFractionDigits: 0})
        }
        $(api.column(columnIdx).footer()).html(result);
    }

    // DataTables renderer for ISK values
    $.fn.dataTable.render.formatisk = function(magnitude=null) {
        return function ( data, type, row ) {
            if ( type === 'display' ) {
                return formatisk(data, magnitude);
            }
            // Search, order and type can use the original data
            return data;
        };
    };
</script>

freight/templates/freight/partials/menu.html
{% load static %}
{% load i18n %}
{% load navactive %}

<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">{% trans "Toggle navigation" %}</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'freight:index' %}">{{ app_title }}</a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                {% if perms.freight.use_calculator %}
                    <li class="{% navactive request 'freight:calculator' %}">
                        <a href="{% url 'freight:calculator' %}">
                            {% translate "Reward Calculator" %}
                        </a>
                    </li>

                    <li class="{% navactive request 'freight:contract_list_user' %}">
                        <a href="{% url 'freight:contract_list_user' %}">
                            {% translate "My Contract" %}s&nbsp;
                            {% if pending_user_count > 0 %}
                                <span class="badge badge-nav">{{ pending_user_count }}</span>
                            {% endif %}
                        </a>
                    </li>
                {% endif %}

                {% if perms.freight.view_contracts %}
                    <li class="{% navactive request 'freight:contract_list_all' %}">
                        <a href="{% url 'freight:contract_list_all' %}">
                            {% translate "All Contracts" %}&nbsp;
                            {% if pending_all_count > 0 %}
                                <span class="badge badge-nav">{{ pending_all_count }}</span>
                            {% endif %}
                        </a>
                    </li>
                {% endif %}

                {% if perms.freight.view_statistics %}
                    <li class="{% navactive request 'freight:statistics' %}">
                        <a href="{% url 'freight:statistics' %}">
                            {% translate "Statistics" %}
                        </a>
                    </li>
                {% endif %}
            </ul>

            <ul class="nav navbar-nav navbar-right">
                {% if perms.freight.add_location %}
                    <a class="btn btn-default navbar-btn" href="{% url 'freight:add_location' %}">
                        {% translate "Add Location" %}
                    </a>
                {% endif %}

                {% if perms.freight.setup_contract_handler %}
                    <a class="btn btn-default navbar-btn" href="{% url 'freight:setup_contract_handler' %}">
                        {{ setup_contract_handler_label }}
                    </a>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>